# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "build"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "build"
    # Allow up to 10 open pull requests for npm dependencies
    open-pull-requests-limit: 10

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "build"
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10

  # Maintain dependencies for pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "girardinsamuel"
    labels:
      - "build"
    target-branch: master
    # Allow up to 10 open pull requests for pip dependencies
    open-pull-requests-limit: 10