name: Bump version

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
      - name: debug
        run: echo $GITHUB_REF
      # - name: Set up Python
      #   uses: actions/setup-python@v2.2.1
      #   with:
      #     python-version: "3.x"
      # - name: Install dependencies
      #   run: |
      #     make init
      # - name: Publish only packages passing test
      #   run: |
      #     make test
      # - name: Bump version
      #   run: cz bump  # --changelog
      # - name: Build and publish
      #   env:
      #     TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
      #     TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      #   run: |
      #     make publish
